name: Common Workflows
on:
  workflow_call:
    inputs:
      ignore_file:
        description: "truffle-hog ignore file"
        type: string
        required: false
jobs:
  TruffleHog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Create trufflehog Ignore file
        run: |
          echo $'# npm\n.*package-lock.json$\n# Yarn\n.*yarn.lock$\n# Helm\n.*requirements.lock$\n# CSS\n.*\.css$\n# SVG\n.*\.svg$' > trufflehog_ignore
      - name: print
        run: |
          cat ./trufflehog_ignore
      - name: TruffleHog OSS
        uses: trufflesecurity/trufflehog@v3.4.3
        with:
          path: ./
          base: ${{ github.event.repository.default_branch }}
          head: HEAD
          extra_args: --debug

  
