name: "Build and Push Docker images to Docker Registry"

on:
  workflow_call:
    inputs:
      image_name:
        description: "Docker image name"
        required: false
        type: string
        default: ${{ github.event.repository.name }}
    secrets:
      service_account_key:
        description: "GCP Service Account Key"
        required: true
      project_id:
        description: "GCP Project ID"
        required: true

jobs:
  build:
    name: docker
    runs-on: ubuntu-22.04
    steps:
      - name: checkout
        uses: actions/checkout@v2
      # Generating the Docker Image Tag
      - name: Docker Image Tag creation
        id: image_tag
        shell: bash
        run: |
          GCR_PROJECT_ID="${{ secrets.project_id }}"
          IMAGE="gcr.io/$GCR_PROJECT_ID/${{ inputs.image_name }}"
          BRANCH="${GITHUB_REF#refs/heads/}"
          SHA="$(git rev-parse --short HEAD)"
          JOB_ID="${GITHUB_RUN_NUMBER}"
          IMAGE_TAG_FULL="$IMAGE:$BRANCH-cijob-$JOB_ID-commit-$SHA"
          echo "IMAGE=$IMAGE" >> $GITHUB_OUTPUT
          echo "IMAGE_TAG_FULL=$IMAGE_TAG_FULL" >> $GITHUB_OUTPUT
          echo ":whale2: Image Tag: ${IMAGE_TAG_FULL} " >> $GITHUB_STEP_SUMMARY
      # Login to GCR
      - name: docker login
        uses: "lagren/docker-gcr-action@master"
        with:
          SERVICE_ACCOUNT_KEY: ${{ secrets.service_account_key }}
          HOST: "gcr.io"
      # Build and push to GCR
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1.5.1
      - name: docker publish image
        uses: docker/build-push-action@v2.6.1
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.image_tag.outputs.IMAGE_TAG_FULL }}
          cache-from: type=gha,mode=max
          cache-to: type=gha,mode=max
