name: "NPM Test"

on:
  workflow_call:
    inputs:
      node_version:
        description: "NodeJs version to be used to build-args"
        type: string
        default: "12.19.1"
        required: false
      test_coverage:
        description: "Enable or Disable Test Coverage"
        default: true
        type: boolean
        required: false
    secrets:
      npm_token:
        description: "NPM Token to access NPM Registry"
        required: false

jobs:
  test:
    name: npm
    runs-on: ubuntu-latest
    container:
      image:  node:16.14
      env:
        NPM_TOKEN: ${{ secrets.npm_token }}
        BRANCH: ${GITHUB_REF#refs/heads/}
      options: --cpus 4 -m 16
    timeout-minutes: 45
    steps:
      # Checkout code
      - name: "Checkout repository on: ${{ github.REF }}"
        uses: actions/checkout@v2
      # Setup node environment
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.1.0
        with:
          node-version: ${{ inputs.node_version }}
      - name: Run tests
        run: |
          npm cache clear --force
          npm install
          npm run lint
          if [ ${{ inputs.test_coverage }} == true ]; then
            npm run test:coverage
          else
            npm run test
          fi
      - name: Output Branch name
        run: |
          echo ":seedling: Branch:${GITHUB_REF#refs/heads/}" >> $GITHUB_STEP_SUMMARY
      - name: upload artifact
        if: (inputs.test_coverage == true)
        uses: actions/upload-artifact@v2
        with:
          name: coverage-output
          path: coverage/    
          
