name: "NPM Test"

on:
  workflow_call:
    inputs:
      node_version:
        description: "NodeJs version to be used to build-args"
        type: string
        default: "12.19.1"
        required: false
    secrets:
      npm_token:
        description: "NPM Token to access NPM Registry"
        required: false

jobs:
  npm-test:
    runs-on: ubuntu-latest
    env:
      NPM_TOKEN: ${{ secrets.npm_token }}
    timeout-minutes: 20
    steps:
      # Checkout code
      - name: "Checkout repository on: ${{ github.REF }}"
        uses: actions/checkout@v2
      # Setup node environment
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.1.0
        with:
          node-version: ${{ inputs.node_version }}
      - name: Run tests
        run: |
          npm cache clear --force
          npm install
          npm run lint
          if [ -z $GITHUB_BASE_REF ]
          then
            npm run test
          else
            npm run test:coverage
          fi
      - name: upload artifact
        if: ${{ env.GITHUB_BASE_REF }} != null
        uses: actions/upload-artifact@v2
        with:
          name: coverage-output
          path: coverage/    
          
