name: "NPM Test"

on:
  workflow_call:
    inputs:
      node_version:
        description: "NodeJs version to be used to build-args"
        type: string
        default: "12.19.1"
        required: false
      test_coverage:
        description: "Enable or Disable Test Coverage"
        default: true
        type: boolean
        required: false
    secrets:
      npm_token:
        description: "NPM Token to access NPM Registry"
        required: false

jobs:
  test:
    name: npm
    runs-on: ubuntu-latest
    env:
      NPM_TOKEN: ${{ secrets.npm_token }}
      BRANCH: ${GITHUB_REF#refs/heads/}
    timeout-minutes: 45
    steps:
      # Checkout code
      - name: "Checkout repository on: ${{ github.REF }}"
        uses: actions/checkout@v2
      # Setup node environment
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.1.0
        with:
          node-version: ${{ inputs.node_version }}
      - name: Run tests
        run: |
          npm cache clear --force
          npm install
          npm run lint
          if [ ${{ inputs.test_coverage }} == true ]; then
            npm run test:coverage
          else
            npm run test
          fi
      - name: Output Branch name
        run: |
          echo ":seedling: Branch:${GITHUB_REF#refs/heads/}" >> $GITHUB_STEP_SUMMARY
      - name: upload artifact
        if: (inputs.test_coverage == true)
        uses: actions/upload-artifact@v2
        with:
          name: coverage-output
          path: coverage/
  migration-check:
    name: check for migration files
    runs-on: ubuntu-latest
    timeout-minutes: 45
    steps:
      # Checkout code
      - name: "Checkout repository on: ${{ github.REF }}"
        uses: actions/checkout@v2

      - name: "Check migration file existence"
        id: file-exists
        uses: andstor/file-existence-action@v1
        with:
          files: "migrations/*.ts"

      - name: Get changed files
        if: ${{ ( steps.file-exists.outputs.files_exists == 'true' ) }}
        id: changed-files
        uses: tj-actions/changed-files@v22.2
        with:
          files: |
            migrations/*.ts

      - name: Comment on PR
        if: ${{ ( github.BASE_REF == 'master' ) && ( steps.changed-files.outputs.all_changed_files ) && ( github.event_name == 'pull_request' ) && ( steps.file-exists.outputs.files_exists == 'true' ) }}
        uses: thollander/actions-comment-pull-request@v1
        with:
          message: |
            :warning: @bukukasio/tokko-leads DB Migration query detected :warning:
          reactions: eyes
          GITHUB_TOKEN: ${{ secrets.npm_token }}

      - name: Edit PR comment
        if: ${{ ( github.BASE_REF == 'master' ) && ( steps.changed-files.outputs.all_changed_files ) && ( github.event_name == 'pull_request' ) && ( steps.file-exists.outputs.files_exists == 'true' ) }}
        uses: thollander/actions-comment-pull-request@v1
        with:
          message: ":warning: @bukukasio/tokko-leads DB Migration query detected :warning:"
          comment_includes: "DB Migration query detected"
          GITHUB_TOKEN: ${{ secrets.npm_token }}

      - name: Create PR review request
        if: ${{ ( github.BASE_REF == 'master' ) && ( steps.changed-files.outputs.all_changed_files ) && ( github.event_name == 'pull_request' ) && ( steps.file-exists.outputs.files_exists == 'true' ) }}
        env:
          GITHUB_TOKEN: ${{ secrets.npm_token }}
        run: |
          gh pr edit ${{ github.event.pull_request.html_url }} \
              --add-reviewer bukukasio/tokko-leads     
      
      - name: Add Label in PR
        if: ${{ ( github.BASE_REF == 'master' ) && ( steps.changed-files.outputs.all_changed_files ) && ( github.event_name == 'pull_request' ) && ( steps.file-exists.outputs.files_exists == 'true' ) }}
        uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: |
            new-db-migration
