name: "Build and Push ReactJS application to GCS Bucket"

on:
  workflow_call:
    inputs:
      BUCKET_NAME: 
        description: "Bucket Name"
        required: true
        type: string
      PROJECT_ID:
        description: "GCP Project ID"
        required: true
        type: string
    secrets:
      SERVICE_ACCOUNT_KEY:
        description: "GCP Service Account Key"
        required: true

jobs:
  build_and_deploy:
    name: Setup
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: 'Checkout repository on: ${{ github.REF }}'
        uses: actions/checkout@v2
      # - name: setup Node
      #   uses: actions/setup-node@v1
      #   with:
      #     node-version: 14.17.1
      #     registry-url: 'https://npm.pkg.github.com'
      # - name: npm install
      #   run: npm install
      # - name: npm test  
      #   run: npm run test
      # - name: npm build
      #   run: npm run build
      - name: test
        run: |
          echo "SERVICE_ACCOUNT_KEY >>>> ${{ secrets.SERVICE_ACCOUNT_KEY }}"
          echo "PROJECT_ID >>>> ${{ inputs.PROJECT_ID }}"
          echo "STATIC_BUCKET_NAME >>>> ${{ inputs.BUCKET_NAME }}"
          if [[ -z "${SERVICE_ACCOUNT_KEY}" ]]; then
              echo "SERVICE_ACCOUNT_KEY is not set"
          fi

          if [[ -z "${PROJECT_ID}" ]]; then
              echo "PROJECT_ID is not set"
          fi

          if [[ -z "${STATIC_BUCKET_NAME}" ]]; then
              echo "STATIC_BUCKET_NAME is not set"
          fi

      # - name: 'Authenticate GCloud'
      #   uses: 'google-github-actions/auth@v0'
      #   with:
      #     credentials_json: '${{ inputs.SERVICE_ACCOUNT_KEY }}'
      # - name: Set up Cloud SDK 
      #   uses: google-github-actions/setup-gcloud@v0
      #   with:
      #     PROJECT_ID: "${{ inputs.PROJECT_ID }}"
      #     export_default_credentials: true


      - name: Cloud Storage Uploader
        uses: google-github-actions/upload-cloud-storage@v0.9.0
        with:
          credentials: "${{ inputs.SERVICE_ACCOUNT_KEY }}"
          path: sample
          destination: "tokko-test-ops2/test"
          parent: false
      # - name: Cloud Storage Uploader
      #   uses: google-github-actions/upload-cloud-storage@v0.9.0
      #   # env:
      #   #   GOOGLE_CLOUD_ACCOUNT: "${{ steps.build_env.outputs.GOOGLE_CLOUD_ACCOUNT }}"
      #   with:
      #     credentials: ${{ secrets.SERVICE_ACCOUNT_KEY }}
      #     path: build
      #     destination: ${{ input.STATIC_BUCKET_NAME }}
      #     parent: false   
      # - name: Invalidate CDN
      #   run: |
      #    gcloud compute url-maps invalidate-cdn-cache ${{steps.build_env.outputs.STATIC_BUCKET_NAME}}-lb --path "/*" --async
      #    echo "CDN invalidation started"
