name: "Build and Push ReactJS application to GCS Bucket"

on:
  workflow_call:
    inputs:
      PROJECT_ID: 
        description: "Project Id"
        required: true
        type: string
      BUCKET_NAME: 
        description: "Bucket Name"
        required: true
        type: string
      PATH:
        description: "Path to upload"
        required: true
        type: string
      GCP_SECRET_NAME:
        description: "GCP Secret for the applicaition"
        required: true
        type: string
      SECRET_PATH:
        description: "Path to copy the application secret"
        required: true
        type: string      
    secrets:
      SERVICE_ACCOUNT_KEY:
        description: "GCP Service Account Key"
        required: true
jobs:
  build_and_deploy:
    name: Setup
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: 'Checkout repository on: ${{ github.REF }}'
        uses: actions/checkout@v2
      # Build & Deploy to Beecash Environment
      - name: Set up Cloud SDK 
        uses: google-github-actions/setup-gcloud@v0.6.0
        env:
          GOOGLE_CLOUD_ACCOUNT: "${{ steps.build_env.outputs.GOOGLE_CLOUD_ACCOUNT }}"
        with:
          project_id: "${{ inputs.PROJECT_ID }}"
          service_account_key:  ${{ secrets.SERVICE_ACCOUNT_KEY }}
          export_default_credentials: true
      - name: Copy GCP Secret
        run: gcloud secrets versions access latest --secret="${{ inputs.GCP_SECRET_NAME }}" > ${{ inputs.SECRET_PATH }}
      # Initialise Node environment
      - name: setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 14.17.1
          registry-url: 'https://npm.pkg.github.com'
      - name: npm install
        run: npm install
      - name: npm test  
        run: npm run test
      - name: npm build
        run: npm run build
      - name: test
        run: |
          cat .env

      - name: Cloud Storage Uploader
        uses: google-github-actions/upload-cloud-storage@v0.9.0
        with:
          credentials: ${{ secrets.SERVICE_ACCOUNT_KEY }}
          path: ${{ inputs.PATH }}
          destination: ${{ inputs.BUCKET_NAME }}
          parent: false   
      - name: Invalidate CDN
        run: |
         gcloud compute url-maps invalidate-cdn-cache ${{steps.build_env.outputs.STATIC_BUCKET_NAME}}-lb --path "/*" --async
         echo "CDN invalidation started"
