name: "Build and Push ReactJS application to GCS Bucket"

on:
  workflow_call:
    inputs:
      PROJECT_ID: 
        description: "Project Id"
        required: true
        type: string
      BUCKET_NAME: 
        description: "Bucket Name"
        required: true
        type: string
      PATH:
        description: "Path to upload"
        required: true
        type: string
      SERVICE_ACCOUNT_KEY:
        description: "GCP Service Account Key"
        required: true
        type: string

jobs:
  build_and_deploy:
    name: Setup
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: 'Checkout repository on: ${{ github.REF }}'
        uses: actions/checkout@v2
      # - name: setup Node
      #   uses: actions/setup-node@v1
      #   with:
      #     node-version: 14.17.1
      #     registry-url: 'https://npm.pkg.github.com'
      # - name: npm install
      #   run: npm install
      # - name: npm test  
      #   run: npm run test
      # - name: npm build
      #   run: npm run build
      - name: test
        run: |
          echo "SERVICE_ACCOUNT_KEY >>>> ${{ inputs.SERVICE_ACCOUNT_KEY }}"
          echo "PROJECT_ID >>>> ${{ inputs.PROJECT_ID }}"
          echo "STATIC_BUCKET_NAME >>>> ${{ inputs.BUCKET_NAME }}"
          if [[ -z "${{ inputs.SERVICE_ACCOUNT_KEY }}" ]]; then
              echo "SERVICE_ACCOUNT_KEY is not set"
          fi

          if [[ -z "${{ inputs.PROJECT_ID }}" ]]; then
              echo "PROJECT_ID is not set"
          fi

          if [[ -z "${{ inputs.BUCKET_NAME }}" ]]; then
              echo "STATIC_BUCKET_NAME is not set"
          fi
          
      - name: Set up Cloud SDK 
        uses: google-github-actions/setup-gcloud@v0.6.0
        env:
          GOOGLE_CLOUD_ACCOUNT: "${{ inputs.SERVICE_ACCOUNT_KEY }}"
        with:
          project_id: "${{ inputs.PROJECT_ID }}"
          service_account_key: ${{ secrets[env.GOOGLE_CLOUD_ACCOUNT] }}
          export_default_credentials: true
      - name: Cloud Storage Uploader
        uses: google-github-actions/upload-cloud-storage@v0.9.0
        env:
          GOOGLE_CLOUD_ACCOUNT: "${{ inputs.SERVICE_ACCOUNT_KEY }}"
        with:
          credentials: ${{ secrets[env.GOOGLE_CLOUD_ACCOUNT] }}
          path: ${{ inputs.PATH }}
          destination: ${{ inputs.BUCKET_NAME }}
          parent: false   
#       - name: Invalidate CDN
      #   run: |
      #    gcloud compute url-maps invalidate-cdn-cache ${{steps.build_env.outputs.STATIC_BUCKET_NAME}}-lb --path "/*" --async
      #    echo "CDN invalidation started"
